name: Actions
on:
  push:
    branches:
      - master
  pull_request:
      branches: [ master ]
jobs:
  部署:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@master
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        BRANCH: gh-pages
        FOLDER: dist
        BUILD_SCRIPT: npm i & npm run build & npx stylus ./dist/main.styl & echo "demo.costream.org" >> ./dist/CNAME
