name: 黑盒测试
on:
  push:
    branches:
      - master
  pull_request:
      branches: [ master ]
jobs:
  black-box-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build
      run: |
        npm i
        npm run build
        npm run test
