name: Actions
on:
  push:
    branches:
      - master
  pull_request:
      branches: [ master ]
jobs:
  单元测试:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Build
      run: |
        npm i
        npm run build
        npm run test
